-- Migration 008 · Shopify-parity admin: core business entities
--
-- Adds the foundational tables every commerce dashboard needs:
--
--   * `customers`           — anyone who has talked to a storefront
--   * `orders`              — finalised purchases + manual drafts
--   * `order_items`         — line items per order (snapshotted at sale time)
--   * `inquiries`           — product-page "Inquire" submissions, optionally
--                             linked to a customer record
--   * `discounts`           — promo codes / automatic offers
--   * `analytics_events`    — append-only page-view + product-view + add-
--                             to-cart events powering the Analytics tab
--   * `audit_log`           — generic admin action history (visible in
--                             Settings → Activity log)
--   * `locations`           — physical pickup / fulfilment points
--   * `domains`             — custom domains attached to a storefront
--   * `metaobjects`         — generic key-value records (custom data)
--
-- All tables key on `storefront_slug` referencing `briefs(slug)` with
-- `on delete cascade`. We never key on `clerk_user_id` directly because
-- a single user can own many storefronts; the storefront row is the
-- unit of multi-tenancy. Owner-gating is enforced in the data helpers,
-- not in the DDL — keeps RLS off the critical path.
--
-- Re-runnable: every alter / create is `if not exists`-guarded. Indexes
-- are tuned for the hot list-and-detail patterns in the dashboard.

begin;

-- -----------------------------------------------------------------------
-- customers · the people who shop / inquire from a storefront
-- -----------------------------------------------------------------------
create table if not exists customers (
  id                 bigserial primary key,
  storefront_slug    text not null
                       references briefs(slug) on delete cascade,
  -- normalised primary identifier (lower-cased email or phone, slug-prefixed
  -- so the same email at two stores stays distinct). Set at insert and
  -- never updated; user-facing fields live below and may change.
  identifier         text not null,
  email              text,
  phone              text,
  first_name         text,
  last_name          text,
  -- arbitrary tags the founder can attach (vip, wholesale, etc).
  -- Stored as a sorted text[] so filters can use && / @>.
  tags               text[] not null default '{}',
  marketing_consent  boolean not null default false,
  -- aggregate fields kept denormalised for cheap list rendering.
  -- Updated by the order/inquiry write paths inside the same txn.
  total_spent        numeric(12, 2) not null default 0,
  order_count        integer not null default 0,
  inquiry_count      integer not null default 0,
  last_seen_at       timestamptz,
  meta               jsonb not null default '{}'::jsonb,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (storefront_slug, identifier)
);

create index if not exists customers_store_created_idx
  on customers (storefront_slug, created_at desc);
create index if not exists customers_store_last_seen_idx
  on customers (storefront_slug, last_seen_at desc nulls last);
create index if not exists customers_email_idx
  on customers (lower(email))
  where email is not null;
create index if not exists customers_phone_idx
  on customers (phone)
  where phone is not null;

-- -----------------------------------------------------------------------
-- orders · finalised purchases and manual draft orders the founder
-- creates from the dashboard. Souqna v1 does not run a checkout, so
-- most rows arrive via "create order" in the admin (matching how many
-- Doha founders close on WhatsApp first, then log the sale).
-- -----------------------------------------------------------------------
create table if not exists orders (
  id                 bigserial primary key,
  storefront_slug    text not null
                       references briefs(slug) on delete cascade,
  customer_id        bigint references customers(id) on delete set null,
  -- human-friendly order name (#1001, #1002…) per storefront. The
  -- sequence is generated by `next_order_number(slug)` below.
  order_number       integer not null,
  -- status drives the list filters and the badge colour
  status             text not null default 'open'
                       check (status in (
                         'open','draft','paid','partially_paid','refunded',
                         'partially_refunded','cancelled','archived'
                       )),
  fulfilment_status  text not null default 'unfulfilled'
                       check (fulfilment_status in (
                         'unfulfilled','partial','fulfilled','restocked'
                       )),
  payment_status     text not null default 'pending'
                       check (payment_status in (
                         'pending','authorized','paid','refunded',
                         'voided','failed'
                       )),
  -- amounts are stored in QAR by default. The `currency_code` column
  -- lets a future markets/MC pricing world support per-order currency
  -- without backfilling.
  currency_code      text not null default 'QAR',
  subtotal           numeric(12, 2) not null default 0,
  discount_total     numeric(12, 2) not null default 0,
  shipping_total     numeric(12, 2) not null default 0,
  tax_total          numeric(12, 2) not null default 0,
  total              numeric(12, 2) not null default 0,
  -- snapshotted shipping address at time of sale
  shipping_address   jsonb,
  billing_address    jsonb,
  notes              text,
  channel            text not null default 'admin'
                       check (channel in ('admin','storefront','inquiry','import')),
  -- discount code applied (string only; the `discounts` row is referenced
  -- by id below). Stored as plain text so analytics doesn't require a join.
  discount_code      text,
  discount_id        bigint,
  meta               jsonb not null default '{}'::jsonb,
  placed_at          timestamptz,
  paid_at            timestamptz,
  cancelled_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (storefront_slug, order_number)
);

create index if not exists orders_store_created_idx
  on orders (storefront_slug, created_at desc);
create index if not exists orders_store_status_idx
  on orders (storefront_slug, status);
create index if not exists orders_customer_idx
  on orders (customer_id)
  where customer_id is not null;

-- per-storefront order number generator. Lives in a side table so we
-- don't burn a sequence on every store and don't have to manage 1000s
-- of postgres sequences. The actual increment-and-return runs in the
-- application layer (src/lib/orders.ts) using a single round-tripped
-- INSERT … ON CONFLICT DO UPDATE RETURNING — so the migration stays
-- pure DDL and the migration runner doesn't need to understand
-- dollar-quoted plpgsql bodies.
create table if not exists order_number_counters (
  storefront_slug text primary key
                    references briefs(slug) on delete cascade,
  next_value      integer not null default 1001
);

-- -----------------------------------------------------------------------
-- order_items · per-line snapshot. Title/price are duplicated so that
-- a product rename or price change does NOT mutate historical orders.
-- -----------------------------------------------------------------------
create table if not exists order_items (
  id              bigserial primary key,
  order_id        bigint not null references orders(id) on delete cascade,
  product_id      text,
  product_title   text not null,
  variant_label   text,
  unit_price      numeric(12, 2) not null,
  quantity        integer not null check (quantity > 0),
  total           numeric(12, 2) not null,
  meta            jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists order_items_order_idx
  on order_items (order_id);
create index if not exists order_items_product_idx
  on order_items (product_id)
  where product_id is not null;

-- -----------------------------------------------------------------------
-- inquiries · "Ask about this" submissions from storefront product pages.
-- Distinct from orders because most leads in Souqna's market never
-- become payment-on-site sales — they convert via WhatsApp / email.
-- -----------------------------------------------------------------------
create table if not exists inquiries (
  id                 bigserial primary key,
  storefront_slug    text not null
                       references briefs(slug) on delete cascade,
  customer_id        bigint references customers(id) on delete set null,
  product_id         text,
  product_title      text,
  message            text not null,
  visitor_name       text,
  visitor_email      text,
  visitor_phone      text,
  preferred_channel  text not null default 'whatsapp'
                       check (preferred_channel in ('whatsapp','email','phone','any')),
  status             text not null default 'new'
                       check (status in ('new','responded','closed','spam')),
  source_url         text,
  user_agent         text,
  meta               jsonb not null default '{}'::jsonb,
  created_at         timestamptz not null default now(),
  responded_at       timestamptz
);

create index if not exists inquiries_store_created_idx
  on inquiries (storefront_slug, created_at desc);
create index if not exists inquiries_store_status_idx
  on inquiries (storefront_slug, status);
create index if not exists inquiries_customer_idx
  on inquiries (customer_id)
  where customer_id is not null;

-- -----------------------------------------------------------------------
-- discounts · promo codes + automatic offers
-- -----------------------------------------------------------------------
create table if not exists discounts (
  id                 bigserial primary key,
  storefront_slug    text not null
                       references briefs(slug) on delete cascade,
  -- 'code' (manual entry) or 'automatic' (apply at cart automatically)
  kind               text not null default 'code'
                       check (kind in ('code','automatic')),
  -- displayed everywhere; for code-discounts also the redemption key.
  code               text not null,
  title              text,
  -- value semantics
  value_type         text not null
                       check (value_type in ('percentage','fixed_amount','free_shipping')),
  value              numeric(12, 2) not null default 0,
  -- limits
  applies_to         text not null default 'all'
                       check (applies_to in ('all','products','categories')),
  applies_to_ids     text[] not null default '{}',
  minimum_subtotal   numeric(12, 2),
  usage_limit        integer,
  per_customer_limit integer,
  used_count         integer not null default 0,
  status             text not null default 'active'
                       check (status in ('active','scheduled','expired','disabled')),
  starts_at          timestamptz,
  ends_at            timestamptz,
  meta               jsonb not null default '{}'::jsonb,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (storefront_slug, code)
);

create index if not exists discounts_store_status_idx
  on discounts (storefront_slug, status);

-- -----------------------------------------------------------------------
-- analytics_events · append-only event log. The Analytics tab aggregates
-- via SQL; we deliberately do not pre-aggregate so adding a new chart is
-- purely a frontend concern.
-- -----------------------------------------------------------------------
create table if not exists analytics_events (
  id              bigserial primary key,
  occurred_at     timestamptz not null default now(),
  storefront_slug text not null
                    references briefs(slug) on delete cascade,
  -- 'page_view' | 'product_view' | 'inquire_open' | 'inquire_submit'
  --   | 'cart_add' | 'cart_remove' | 'order_placed' | 'discount_applied'
  --   | 'app_event' (free-form for plugins)
  kind            text not null,
  -- cookie-derived anonymous id (set client-side, ttl 1 yr). NOT a PII.
  visitor_id      text,
  -- best-effort session id, rotated every 30 min of inactivity.
  session_id      text,
  -- for product views / cart events
  product_id      text,
  -- referrer host / utm_source bucket so the dashboard can roll up
  -- "Top referrers" without a substring scan of meta.
  referrer_host   text,
  -- {path, country, ua, utm_*, value, currency, etc.}
  meta            jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_store_time_idx
  on analytics_events (storefront_slug, occurred_at desc);
create index if not exists analytics_events_store_kind_time_idx
  on analytics_events (storefront_slug, kind, occurred_at desc);
create index if not exists analytics_events_product_time_idx
  on analytics_events (product_id, occurred_at desc)
  where product_id is not null;

-- -----------------------------------------------------------------------
-- audit_log · "who did what when" log for the Settings → Activity log
-- screen. Kept separate from souqy_audit because that table is keyed on
-- Clerk user id; this one is keyed on storefront so the per-store
-- activity log doesn't fan out.
-- -----------------------------------------------------------------------
create table if not exists audit_log (
  id              bigserial primary key,
  occurred_at     timestamptz not null default now(),
  storefront_slug text not null
                    references briefs(slug) on delete cascade,
  clerk_user_id   text not null,
  -- 'product.create', 'product.update', 'order.create', 'order.refund',
  -- 'discount.create', 'settings.update', 'app.install', 'app.uninstall',
  -- 'storefront.publish', 'storefront.theme_update', 'inquiry.respond', …
  action          text not null,
  -- free-form id of the resource the action targeted (product id, order
  -- id as string, app id, etc).
  target_id       text,
  -- summary text rendered in the activity feed without needing to
  -- hydrate the full target row.
  summary         text,
  meta            jsonb not null default '{}'::jsonb
);

create index if not exists audit_log_store_time_idx
  on audit_log (storefront_slug, occurred_at desc);
create index if not exists audit_log_user_time_idx
  on audit_log (clerk_user_id, occurred_at desc);

-- -----------------------------------------------------------------------
-- locations · physical pickup / fulfilment points. Defaulted to one
-- "Primary" row per store at the first list-page render so the UI
-- never has to render an empty state for a single-location founder.
-- -----------------------------------------------------------------------
create table if not exists locations (
  id              bigserial primary key,
  storefront_slug text not null
                    references briefs(slug) on delete cascade,
  name            text not null,
  is_primary      boolean not null default false,
  fulfils_orders  boolean not null default true,
  address         jsonb not null default '{}'::jsonb,
  phone           text,
  email           text,
  hours           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists locations_primary_per_store
  on locations (storefront_slug)
  where is_primary;
create index if not exists locations_store_idx
  on locations (storefront_slug);

-- -----------------------------------------------------------------------
-- domains · custom domains the founder has attached. Verification status
-- is updated by the Vercel domains integration.
-- -----------------------------------------------------------------------
create table if not exists domains (
  id              bigserial primary key,
  storefront_slug text not null
                    references briefs(slug) on delete cascade,
  hostname        text not null unique,
  status          text not null default 'pending'
                    check (status in ('pending','verified','error','removed')),
  is_primary      boolean not null default false,
  redirect_root   boolean not null default true,
  meta            jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  verified_at     timestamptz
);

create index if not exists domains_store_idx
  on domains (storefront_slug);

-- -----------------------------------------------------------------------
-- metaobjects · the "custom data" surface (FAQ entries, testimonials,
-- press logos, anything the founder wants to define a structure for and
-- bind to blocks). Stored as namespace+kind+key to mirror Shopify's
-- metaobject taxonomy without forcing schema migrations.
-- -----------------------------------------------------------------------
create table if not exists metaobjects (
  id              bigserial primary key,
  storefront_slug text not null
                    references briefs(slug) on delete cascade,
  namespace       text not null default 'app',
  kind            text not null,
  key             text not null,
  fields          jsonb not null default '{}'::jsonb,
  display_name    text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (storefront_slug, namespace, kind, key)
);

create index if not exists metaobjects_store_kind_idx
  on metaobjects (storefront_slug, kind);

commit;
